version: '3.7'

services:
  db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ['--requirepass "secret"']
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    container_name: "api"
    command: /usr/src/app/node_modules/.bin/ts-node-dev --transpile-only --no-notify src
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - APP_PORT=5000
      - APP_HOSTNAME=localhost
      - APP_PROTOCOL=http
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=secret
      - MONGO_HOST=127.0.0.1
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth
      - SMTP_USERNAME=27464e33c65c48
      - SMTP_PASSWORD=aabe1572c48056
    depends_on:
      - db
      - cache
    networks:
      - app-network
networks:
  app-network:
    driver: bridge